version: "3.0"
services:
  nginx:
    container_name: proxy
    image: "nginx:1.23.4-alpine"
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
      - ./media:/media
    depends_on:
      - uploader
    ports:
      - "80:80"
    links:
      - uploader

  db:
    container_name: database
    image: "postgres:15-alpine"
    restart: always
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_DB: "dev"
      POSTGRES_USER: "devuser"
      POSTGRES_PASSWORD: "devpassword"
    volumes:
      - ./postgres/.init:/docker-entrypoint-initdb.d
      - ./postgres/pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

  redis:
    container_name: redis
    image: "redis:6.2.6-alpine"
    restart: always
    environment:
      REDIS_ARGS: "--requirepass devpassword"
    volumes:
      - ./redis/data:/data
    ports:
      - "6379:6379"

  solr:
    container_name: solr
    image: "solr:9.2.0"
    restart: always
    ports:
      - "8983:8983"
    volumes:
      - ./solr:/var/solr
      - ./solr/security.json:/var/solr/data/security.json

  uploader:
    container_name: uploader
    image: "starponyprod/image-uploader:1.0"
    restart: always
    volumes:
      - ./uploader/application.yaml:/application.yaml
      - ./media:/media
      - ./uploader/logs:/logs